services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: news-agent-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/healthz')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - news-agent-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: news-agent-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - news-agent-network

networks:
  news-agent-network:
    driver: bridge

volumes:
  # Reserved for future database volumes
  postgres_data: